
class Autogenerated {
  String text;
  String author;

  Autogenerated({this.text, this.author});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
        text: json['text'],
        author: json['author'],
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['text'] = this.text;
    data['author'] = this.author;
    return data;
  }
}