import 'dart:async';
import 'dart:convert';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:quotes_season/modal.dart';
import 'package:http/http.dart' as http;

class Quote extends StatefulWidget {
  @override
  _QuoteState createState() => _QuoteState();
}

Future<List<Autogenerated>> fetchQuote() async {
  final response =
  await http.get('https://type.fit/api/quotes');

  if (response.statusCode == 200) {
    // If the server did return a 200 OK response,
    List jsonList = json.decode(response.body);
    List list = jsonList.map((elem) => Autogenerated.fromJson(elem)).toList();
    return list;
  }
  else {
    // If the server did not return a 200 OK response,
    // then throw an exception.
    throw Exception('Failed');
  }
}

class _QuoteState extends State<Quote> {
  Future<List<Autogenerated>> futureAutogenerated;

  @override
  void initState() {
    super.initState();
    futureAutogenerated = fetchQuote();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        padding: EdgeInsets.all(20),
        child: Container(
          child: FutureBuilder(
              future: futureAutogenerated,
              builder: (context, snapshot) {
                if(snapshot.hasData) {
                  return ListView.builder(itemCount: snapshot.data.length, itemBuilder: (context, index) => Container(
                    height: 90,
                    child: Card(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          Text(
                            "${snapshot.data[index].text}",
                            style: TextStyle(
                              fontSize: 18
                            ),
                          ),
                          Text(
                            "- ${snapshot.data[index].author}",
                            style: TextStyle(
                              fontWeight: FontWeight.bold,
                              fontStyle: FontStyle.italic
                            ),
                          )
                        ],
                      ),
                    ),
                  ));
                }else if(snapshot.hasError) {
                  return Center(child: Text("${snapshot.error}"));
                }

                return Center(
                  child: CircularProgressIndicator(),
                );
              }),
        )
      ),
    );
  }
}

